unicomcity:
  server:
    port: 8005
    contextPath: /demo
    acceptorThreadCount: 4
    minSpareThreads: 50
    maxSpareThreads: 50
    maxThreads: 1000
    maxConnections: 10000
    connectionTimeout: 10000
    protocol: org.apache.coyote.http11.Http11Nio2Protocol
    basedirectory: d:/log
    redirectPort: 443
    compression: on
    MaxFileSize: 300MB
    MaxRequestSize: 500MBArith
# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
spring:
  devtools:
    restart:
      # 热部署开关
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root123
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    filter:
      stat:
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
#mybatis-plus 驼峰模式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true